### ISSUE TITLE
AGORA - AdWords Audit

### ISSUE THREAD

**Issue by MajVicious** [MajVicious/docs#1]
# AGORA PPC Audit Guide

## Date Range
- [ ]  Last 3 Month

## KPIs
- [ ]  Check Conversion Tracking

## Settings
- [ ]  Search and Display Targeting
- [ ]  Device Bid Modifiers
- [ ]  Ad delivery method
- [ ]  Ad rotation
- [ ]  location / language targeting
- [ ]  ad sheduling

### Campaigns
- [ ]  Naming structure
- [ ]  Search or Display Targeting
- [ ]  Interest Category or Topics broken out into their own campaigns

### Ad Groups
- [ ]  each Ad Group max. of 20 keywords
- [ ]  are AdGroup logical subcategories of the main campaigns topic

### Keywords
- [ ]  Review Match Types
- [ ]  Are all mathc types in place?
- [ ]  Review negative Keywords - is there a logical exclusion list
- [ ]  Review Search Term Report
- [ ]  Do converting search still need to be addes to the account structure?

### Ads
- [ ]  Grammatically correct
- [ ]  are ads taking advantage of permitted punctiuation
- [ ]  are ads promting prices or offers
- [ ]  have offers expired already?
- [ ]  are there any actice ad tests?

### Quality Score
- [ ]  Check Quality Score Distribution over Positions (Scatter Plot)
- [ ]  Segment out display keywords
- [ ]  Filter out keywords with no QS
- [ ]  Filter out non active keywords (maybe)
- [ ]  Include only eligible keywords

##### Overall Health
- [ ] Aggregate impressions (or clicks) over quality scores
- [ ] The more % over QS 7, the better

##### Spend opportunities
- [ ]  AdGroups, sum(costs), avg(qs)
- [ ]  Look for AdGroups where we have high spends and poor QS
- [ ]  Weight Quality Score by Impressions (QS - [ ]  Impressions)
- [ ]  Devide again by number of impressions ((QS- [ ] Impr)/Impr) to get normalized QS

##### Find Keywords with low QS (< 4)
- [ ]  AdGroup, count(Keywords), qs < 4, order by count(keywords) desc

## Extensions
- [ ]  are extensions in use
- [ ]  call extensions in place
- [ ]  call extension turned on during call center ours

## Networks (Display only)
- [ ]  manages placements used or are all placements running automatically?
- [ ]  are placements converting?
- [ ]  are there useless placements?

## Remarketing
- [ ]  are RM campaigns or audiences implemented?
- [ ]  are they collecting members?
- [ ]  is there an audience for each abandonment level

## Analyics
- [ ]  GA in place?
- [ ]  properly linked to adwords?
- [ ]  Conversions imported to adwords?
- [ ]  Conversion goals different from AdWords?

**Comment by burakcasumo** [comment]
what purpose does this issue have please?
